#--------------------------------------------------
# Build worker image (VM template)
#--------------------------------------------------
image: Visual Studio 2019

#--------------------------------------------------
# Environment
#--------------------------------------------------
environment:
  GITHUB_PERSONAL_ACCESS_TOKEN:
    secure: PNVFwcCuNr+X7SffsiwiVsa/JzVyZqwNJUbeve+Or/EjOwZxbd1CUC0K/5az9jsT    
  GIT_CONFIG_USER_EMAIL:
    secure: yAZjzbVhtfeKof5pGJ/N65IjSffBIJoX5MZIpqbtHkc=

#--------------------------------------------------
# Branch whitelist
#--------------------------------------------------
branches:
  # Whitelist
  only:
    - master

# Do not build on tags, since we auto-commit tags.
skip_tags: true

#--------------------------------------------------
# After cloning repository
#--------------------------------------------------
install:
  - git submodule init
  - git submodule update
  - gitversion

#--------------------------------------------------
# Build configuration
#--------------------------------------------------
configuration: Release

#--------------------------------------------------
# Build command
#--------------------------------------------------
build:
  # Publish symbols, as per: https://www.appveyor.com/docs/build-phase/#packaging-symbols
  publish_nuget: false
  publish_nuget_symbols: true
  use_snupkg_format: true

#--------------------------------------------------
# Build hooks - before
#--------------------------------------------------
before_build:
# Restore
  - dotnet restore
    
#--------------------------------------------------
# Testing
#--------------------------------------------------
test:
  assemblies:
    only:
      - '**\*.Tests.dll' 
#--------------------------------------------------
# Build hooks - on_success
#
# Tags the repository in GitHub with the release version.
#--------------------------------------------------
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GITHUB_PERSONAL_ACCESS_TOKEN):x-oauth-basic@github.com`n"
  - git config --global user.email "%GIT_CONFIG_USER_EMAIL%"
  - git config --global user.name "One Frame Link"
  - git tag "v%APPVEYOR_BUILD_VERSION%"
  - git push origin "v%APPVEYOR_BUILD_VERSION%"
 
#--------------------------------------------------
# NuGet config
#--------------------------------------------------
nuget:
  # disable publishing of .nupkg artifacts to
  # account/project feeds for pull request builds
  disable_publish_on_pr: true

#--------------------------------------------------
# Deploy NuGet
#--------------------------------------------------
deploy:
  provider: NuGet
  api_key:
    secure: WuVzz7rQXKtG8gCcxuBARSPLoFyAed/9ymDhqOPwCSbigHBDRCHPmVv7LKHf8Q5B
  skip_symbols: false
  
#--------------------------------------------------
# Notifications
#--------------------------------------------------
notifications:
  - provider: Slack
    incoming_webhook:
      secure: Y4pw1Q3aqUk/4aVYHN5R3u5Zca5ijyVi6tRAVahXhlGjSMr0ww/5c/YkAUxgtLxNfmJ5bhF5wacHko2xG2tucEIGNnRc5zHgx9/Mab6bgFo=